version: '3.8'

services:
  app:
    container_name: rate_counter_fastapi
    build: .
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/${DB_PORT}; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT}'
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
  db:
    container_name: rate_counter_fastapi_db
    image: postgres:15-alpine
    env_file:
      - .env
    command: -p ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
volumes:
  postgres_data:
